version: '3'
services:
  db:
    user: root
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=db_johndoe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
